name: Snake generator

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" #  run every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.2.0
        with:
          # github user name to read the contribution graph from (**required**)
          github_user_name: ${{ github.repository_owner }}

          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg?color_snake=#ff4500&color_dots=#e6f7ff,#99ccff,#3399ff,#0073e6,#003366
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#ff4500&color_dots=#e6f7ff,#99ccff,#3399ff,#0073e6,#003366
            dist/ocean.gif?color_snake=#ff4500&color_dots=#e6f7ff,#99ccff,#3399ff,#0073e6,#003366

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
